# Generated by Django 3.2 on 2024-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'г'), ('кг', 'кг'), ('л', 'л'), ('мл', 'мл'), ('шт', 'шт')], max_length=4, verbose_name='Единицы измерения'),
        ),
    ]
